### PR TITLE
Fix missing user id in JWT token signing

### PR DESCRIPTION
**Pull request by huilunang**

### CODE REVIEW

**Comment by nfebe** [comment]
@Green-Ranger11 You worked on the JWT thing, can you please first review this?

**Comment by nfebe** [comment]
@huilunang there are merged conflicts for you to resolve.

**Review by Green-Ranger11 — APPROVED** [review]
Yep this was a typo on my end. Thanks for the fix Huilun! LGTM!

**Comment by nfebe** [comment]
Thanks @huilunang ! Merged.

**Pull request merged**
